repos:
  - repo: local
    hooks:
      - id: sync-claude-gemini-commands
        name: Sync .claude and .gemini commands
        entry: python sync_commands.py
        language: python
        files: '^\.claude/commands/.*\.md$'
        pass_filenames: false
        additional_dependencies: []